apiVersion: v1
kind: ConfigMap
metadata:
  name: pulsewatch-db-init
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS request_metrics (
        id SERIAL PRIMARY KEY,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        endpoint VARCHAR(255),
        status_code INTEGER,
        latency DOUBLE PRECISION
    );

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pulsewatch-db-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/local/pulsewatch-db
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pulsewatch-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsewatch-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulsewatch-db
  template:
    metadata:
      labels:
        app: pulsewatch-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "pulsewatch"
            - name: POSTGRES_PASSWORD
              value: "pulsewatch"
            - name: POSTGRES_DB
              value: "pulsewatch"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: pulsewatch-db-pvc
        - name: init-script
          configMap:
            name: pulsewatch-db-init

---
apiVersion: v1
kind: Service
metadata:
  name: pulsewatch-db
spec:
  selector:
    app: pulsewatch-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP